package app_utility;

public enum Constants {
    OPEN_FRAGMENT_MANAGER,
    UPDATE_SECOND_ADAPTER,
    UPDATE_PRODUCTS_ADAPTER,
    OPEN_ALL_PRODUCTS,
    OPEN_INDIVIDUAL_PRODUCT_FRAGMENT,
    UPDATE_PROGRESS_STATUS,
    UPDATE_SECOND_SC_TO_ACTIVITY,
    SEND_SECOND_SC_TO_ALL_FRAGMENT,
    UPDATE_SUB_HEADING,
    IMAGE_CLICKED
}
