package app_utility;

public enum Constants {
    OPEN_FRAGMENT_MANAGER,
    UPDATE_SECOND_ADAPTER,
    UPDATE_PRODUCTS_ADAPTER,
    OPEN_ALL_PRODUCTS,
    OPEN_INDIVIDUAL_PRODUCT_FRAGMENT,
    SUB_CATEGORY_HEADING_UPDATE
}
